# This workflow is triggered when a new version tag (`vX.Y.Z`) is push on branch `main`;
# this relies on lightweight tags (see below, and see the `postversion` script in `package.json`).

name: Publish extension

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

concurrency:
  group: "publish-extension"
  cancel-in-progress: true

jobs:
  publish-extension:
    # Note: `github.event.base_ref` is equal to `refs/heads/main` when the workflow is triggered
    # by a branch, or a lightweight tag (_not_ an annotated tag), placed on the last commit of the `main` branch
    if: github.event.base_ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "nvmrc=$(cat .nvmrc)" >> $GITHUB_ENV
        id: nvmrc

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.nvmrc }}"
          cache: npm

      - run: npm ci

      - env:
          VSCE_PAT: "${{ secrets.VSCE_PAT }}"
        run: npm run vscode:publish

      - env:
          OVSX_PAT: "${{ secrets.OVSX_PAT }}"
        run: npm run openvsx:publish

      # - name: Setup tmate session
      #   if: ${{ always() }}
      #   timeout-minutes: 30 # Run `sudo shutdown -h now` to terminate the session
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   uses: mxschmitt/action-tmate@v3
